//
//  Coin.swift
//  FakeBithumbAssignment
//
//  Created by chihoooon on 2022/03/01.
//

import Foundation

enum Coin: String, CaseIterable {
    case BTC
    case ETH
    case BNB
    case XRP
    case LUNA
    case SOL
    case ADA
    case DOT
    case DOGE
    case MATIC
    case CTO
    case DAI
    case ATOM
    case LTC
    case LINK
    case UNI
    case TRX
    case BCH
    case ALGO
    case MANA
    case XLM
    case ETC
    case SAND
    case AXS
    case VET
    case EGLD
    case THETA
    case KLAY
    case XTZ
    case EOS
    case AAVE
    case MKR
    case WAVES
    case BTT
    case CAKE
    case GALA
    case GRT
    case BSV
    case XEC
    case ENJ
    case CHZ
    case KSM
    case BAT
    case LRC
    case XEM
    case TFUEL
    case XYM
    case BORA
    case COMP
    case YFI
    case WEMIX
    case QTUM
    case BNT
    case WAXP
    case ANKR
    case OMG
    case UMA
    case LPT
    case BTG
    case RLY
    case ZIL
    case ICX
    case ONT
    case NFT
    case ZRX
    case NU
    case SNX
    case WOO
    case IOST
    case GLM
    case SUSHI
    case HIVE
    case UOS
    case JST
    case CKB
    case REN
    case OCEAN
    case CELR
    case C98
    case KNC
    case SRM
    case SXP
    case POWR
    case CHR
    case COTI
    case ALICE
    case FX
    case MED
    case ONG
    case CTSI
    case ORBS
    case PUNDIX
    case BOBA
    case MXC
    case SNT
    case RSR
    case ELF
    case BFC
    case NMR
    case ORC
    case OXT
    case REP
    case DAO
    case RLC
    
    var rawValue: String {
        switch self {
        case .BTC:      return "비트코인"
        case .ETH:      return "이더리움"
        case .BNB:      return "바이낸스코인"
        case .XRP:      return "리플"
        case .LUNA:     return "루나"
        case .SOL:      return "솔라나"
        case .ADA:      return "에이다"
        case .DOT:      return "폴카닷"
        case .DOGE:     return "도지코인"
        case .MATIC:    return "폴리곤"
        case .CTO:
            return "크립토닷컴체인"
        case .DAI:
            return "다이"
        case .ATOM:
            return "코스모스"
        case .LTC:
            return "라이트코인"
        case .LINK:
            return "체인링크"
        case .UNI:
            return "유니스왑"
        case .TRX:
            return "트론"
        case .BCH:
            return "비트코인 캐시"
        case .ALGO:
            return "알고랜드"
        case .MANA:
            return "디샌트럴랜드"
        case .XLM:
            return "스텔라루멘"
        case .ETC:
            return "이더리움 클래식"
        case .SAND:
            return "샌드박스"
        case .AXS:
            return "엑시인피니티"
        case .VET:
            return "비체인"
        case .EGLD:
            return "엘론드"
        case .THETA:
            return "세타토큰"
        case .KLAY:
            return "클레이튼"
        case .XTZ:
            return "테조스"
        case .EOS:
            return "이오스"
        case .AAVE:
            return "에이브"
        case .MKR:
            return "메이커"
        case .WAVES:
            return "웨이브"
        case .BTT:
            return "비트토렌트"
        case .CAKE:
            return "팬케이크스왑"
        case .GALA:
            return "갈라"
        case .GRT:
            return "더그래프"
        case .BSV:
            return "비트코인에스브이"
        case .XEC:
            return "이캐시"
        case .ENJ:
            return "엔진코인"
        case .CHZ:
            return "칠리즈"
        case .KSM:
            return "쿠사마"
        case .BAT:
            return "베이직어텐션토큰"
        case .LRC:
            return "루프링"
        case .XEM:
            return "넴"
        case .TFUEL:
            return "쎄타퓨엘"
        case .XYM:
            return "심볼"
        case .BORA:
            return "보라"
        case .COMP:
            return "컴파운드"
        case .YFI:
            return "연파이낸스"
        case .WEMIX:
            return "위믹스"
        case .QTUM:
            return "퀀텀"
        case .BNT:
            return "뱅코르"
        case .WAXP:
            return "왁스"
        case .ANKR:
            return "앵커"
        case .OMG:
            return "오미세고"
        case .UMA:
            return "우마"
        case .LPT:
            return "라이브피어"
        case .BTG:
            return "비트코인 골드"
        case .RLY:
            return "랠리"
        case .ZIL:
            return "질리카"
        case .ICX:
            return "아이콘"
        case .ONT:
            return "온톨로지"
        case .NFT:
            return "에이피이앤에프티"
        case .ZRX:
            return "제로엑스"
        case .NU:
            return "누사이퍼"
        case .SNX:
            return "신세틱스"
        case .WOO:
            return "우네트워크"
        case .IOST:
            return "이오스트"
        case .GLM:
            return "골렘"
        case .SUSHI:
            return "스시스왑"
        case .HIVE:
            return "허아부"
        case .UOS:
            return "울트라"
        case .JST:
            return "저스트"
        case .CKB:
            return "너보스"
        case .REN:
            return "렌"
        case .OCEAN:
            return "오션프로토콜"
        case .CELR:
            return "셀러네트워크"
        case .C98:
            return "코인98"
        case .KNC:
            return "카이버 네트워크"
        case .SRM:
            return "세럼"
        case .SXP:
            return "스와이프"
        case .POWR:
            return "파워렛저"
        case .CHR:
            return "크로미아"
        case .COTI:
            return "코티"
        case .ALICE:
            return "마이네이버앨리스"
        case .FX:
            return "펑션엑스"
        case .MED:
            return "메디블록"
        case .ONG:
            return "온톨로지가스"
        case .CTSI:
            return "카르테시"
        case .ORBS:
            return "오브스"
        case .PUNDIX:
            return "펀디엑스"
        case .BOBA:
            return "보바토큰"
        case .MXC:
            return "머신익스체인지코인"
        case .SNT:
            return "스테이터스네트워크토큰"
        case .RSR:
            return "리저브라이트"
        case .ELF:
            return "엘프"
        case .BFC:
            return "바이프로스트"
        case .NMR:
            return "뉴메레르"
        case .ORC:
            return "오르빗 체인"
        case .OXT:
            return "오키드"
        case .REP:
            return "어거"
        case .DAO:
            return "다오메이커"
        case .RLC:
            return "아이젝"
        }
    }
}
