# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'FakeBithumbAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FakeBithumbAssignment

  target 'FakeBithumbAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Starscream', '~> 4.0.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then', '~> 2.7.0'

end
